### ISSUE TITLE
Argument of type * is not assignable to parameter of type 'ThemedStyledFunction<any, any, any>'

### ISSUE THREAD

**Issue by baohouse** [jacob-ebey/styled-components-ts#10]
<img width="832" alt="screen shot 2018-04-14 at 1 01 29 pm" src="https://user-images.githubusercontent.com/4228012/38772107-1b46a50e-3fe4-11e8-8001-80890602f961.png">

I don't suppose you've ever had to deal with React components from a third-party library that has its own types. I'm getting this error:
```
Argument of type 'typeof Spin' is not assignable to
parameter of type 'ThemedStyledFunction<any, any, any>'.
Property 'attrs' is missing in type 'typeof Spin'.
```

**Comment by jacob-ebey** [comment]
You have to wrap the component in a styled-component function, see the PR #14

**Comment by jacob-ebey** [comment]
https://github.com/jacob-ebey/styled-components-ts/blob/master/examples/ThirdParty.tsx
