### ISSUE TITLE
No exported member 'StyledComponentClass'

### ISSUE THREAD

**Issue by elie222** [jacob-ebey/styled-components-ts#18]
I get this error when using this package:

```txt
project/node_modules/styled-components-ts/lib/styled-components-ts.d.ts
(3,32): Module '"project/node_modules/@types/styled-components/index"' has no exported member 'StyledComponentClass'. Did you mean 'StyledComponentBase'?
```

Any idea?

```json
    "styled-components": "^4.1.2",
    "styled-components-ts": "^0.0.15"
```

**Comment by elie222** [comment]
I got things working without this package doing something like this:

```ts
const Button = styled.div<{ selected?: boolean }>`
  background: ${props => props.selected ? 'red' : 'blue'};
`
```

**Comment by jacob-ebey** [comment]
This package should ultimately be useless with the latest version of styled-components and the latest pre-released typescript version.

**Comment by mrmartineau** [comment]
@elie222 I had no idea that this could be done, thank you. It looks like this package is redundant now. Thanks for creating it @jacob-ebey 👍

**Comment by jacob-ebey** [comment]
NP, I'm just hoping the styled-components group updates their docs (as I can no longer locate the original issue that sparked this library. There was a fairly long thread on why this wasn't possible before with a link to the typescript fix that allowed a fix.

**Comment by jacob-ebey** [comment]
Thanks for the docs PR @mrmartineau!

**Comment by elie222** [comment]
Their docs are pretty bad btw. I think the two lines of sample code I stuck above actually do a better job of explaining how it's used.

**Comment by danielkcz** [comment]
It looks like that trying to style a custom component (not just div) is still not working? I do have the latest React and SC types packages and TypeScript 3.2.1.

![image](https://user-images.githubusercontent.com/1096340/49362773-f5fdf000-f6df-11e8-894b-123e0ab0af20.png)
