### ISSUE TITLE
NPM package >=0.0.9 is incomplete

### ISSUE THREAD

**Issue by baohouse** [jacob-ebey/styled-components-ts#9]
When I load the NPM package of 0.0.8, it has the following in the `node_modules` folder:

```
LICENSE
README.md
dist
examples
node_modules
package.json
src
typings
```

Any version >=0.0.9 has the following in its folder:

```
LICENSE
README.md
node_modules
package.json
src
```

**Comment by baohouse** [comment]
@jacob-ebey Oh I see you're trying to fix the build/publish flow.

Well if anyone is facing this problem stick to 0.0.8 until this issue is resolved.

**Comment by jacob-ebey** [comment]
I re-opened issue #1. Track that issue for when the resolution goes in.

It should be as simple as adding a 'persist to workspace' command and verifying the whitelist for the circleci config. If you wish to do that and bump the npm version I'll merge your PR. If not I'll jump on this tonight.

I'm going to close this ad a duplicate, thanks :)

**Comment by jacob-ebey** [comment]
Should be good to go in version 0.0.13. See #1 for more info on new package structure.
